<?php

namespace ConstructionsIncongrues\ComThibaultHuertasWwwBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	public function getPrevious(\Datetime $dateReleased)
	{
		$results = $this->createQueryBuilder('p')
			->where('p.is_enabled = true')
			->andWhere('p.date_released > :date')
			->setParameter('date', $dateReleased)
			->orderBy('p.date_released', 'ASC')
			->setMaxResults(1)
			->getQuery()
			->getResult();

		$return = null;
		if ($results) {
			$return = $results[0];
		}
		return $return;
	}

	public function getNext(\Datetime $dateReleased)
	{
		$results = $this->createQueryBuilder('p')
			->where('p.is_enabled = true')
			->andWhere('p.date_released < :date')
			->setParameter('date', $dateReleased)
			->orderBy('p.date_released', 'DESC')
			->setMaxResults(1)
			->getQuery()
			->getResult();

		$return = null;
		if ($results) {
			$return = $results[0];
		}
		return $return;
	}
}
