_welcome:
    pattern:  /
    defaults: { _controller: ConstructionsIncongruesComThibaultHuertasWwwBundle:Default:index }

constructions_incongrues_com_thibault_huertas_www:
    resource: "@ConstructionsIncongruesComThibaultHuertasWwwBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
