# @see http://sonata-project.org/bundles/admin/master/doc/reference/getting_started.html
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_welcome:
    pattern:  /
    defaults: { _controller: ConstructionsIncongruesComThibaultHuertasWwwBundle:Default:index }

constructions_incongrues_com_thibault_huertas_www:
    resource: "@ConstructionsIncongruesComThibaultHuertasWwwBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
