services:
   constructionsincongrues.comthibaulthuertas.admin.project:
      class: ConstructionsIncongrues\ComThibaultHuertasWwwBundle\Admin\ProjectAdmin
      arguments: [ null, ConstructionsIncongrues\ComThibaultHuertasWwwBundle\Entity\Project, SonataAdminBundle:CRUD ]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Website, label: Project }
      calls: 
        - [setTranslationDomain, [ConstructionsIncongruesComThibaultHuertasWwwBundle]]
